In [31]:
# Contoh 2.20.1 Perintah Dasar pada Numpy

import numpy as np

digit_1_98 = np.array([2,1,5,3,9,12,18,20,15])
print(digit_1_98)

print('Jumlah dimensi:', digit_1_98.ndim)
print('Shape:', digit_1_98.shape)

[ 2  1  5  3  9 12 18 20 15]
Jumlah dimensi: 1
Shape: (9,)


In [32]:
# Contoh 2.20.1 Perintah Dasar pada Numpy

import numpy as np

A_1_98 = np.array([8, 2, 9, 4, 12, 11, 5, 7])
B_2_98 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print('Jumlah dimensi 1:', A_1_98.ndim)  
print('Jumlah dimensi 2:', B_2_98.ndim)  

print('Bentuk array 1:', A_1_98.shape)  
print('Bentuk array 2:', B_2_98.shape)  

Jumlah dimensi 1: 1
Jumlah dimensi 2: 2
Bentuk array 1: (8,)
Bentuk array 2: (3, 3)


In [34]:
# Contoh 2.20.2 Memanggil Anggota, Kolom dan Baris dengan Numpy

import numpy as np
nilai_98 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print (nilai_98)

nilai_1_98 = nilai_98[1,2] = 55
print (nilai_98)

nilai_98[0,1]
print('nilai:', nilai_98)
nilai_98[:,2]
nilai_98[1,:]
nilai_98[0,0:2:3]
nilai_98[0,2:1]
print('nilai:', nilai_98)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6 55  8]
 [ 9 10 11 12]]
nilai: [[ 1  2  3  4]
 [ 5  6 55  8]
 [ 9 10 11 12]]
nilai: [[ 1  2  3  4]
 [ 5  6 55  8]
 [ 9 10 11 12]]


In [35]:
# Contoh 2.20.3 Matrix pada Numpy

import numpy as np

angka_1_98 = np.ones((3,3))*2
angka_2_98 = np.identity(3)*5
angka_3_98 = angka_1_98 + angka_2_98
print(angka_3_98 )

[[7. 2. 2.]
 [2. 7. 2.]
 [2. 2. 7.]]


In [36]:
# Contoh 2.20.3 Matrix pada Numpy

import numpy as np

kategori_1_98 = np.zeros((5,5))
print(kategori_1_98)

kategori_2_98 = np.identity(8)
print(kategori_2_98)

kategori_3_98 = 4*kategori_2_98
print(kategori_3_98)

kategori_4_98 = np.random.randint(10, size=(3, 3))
print(kategori_4_98)

kategori_5_98 = np.ones((7,7))
kategori_6_98 = np.identity(7)*7
kategori_7_98 = kategori_5_98 + kategori_6_98
print(kategori_7_98)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]
[[4. 0. 0. 0. 0. 0. 0. 0.]
 [0. 4. 0. 0. 0. 0. 0. 0.]
 [0. 0. 4. 0. 0. 0. 0. 0.]
 [0. 0. 0. 4. 0. 0. 0. 0.]
 [0. 0. 0. 0. 4. 0. 0. 0.]
 [0. 0. 0. 0. 0. 4. 0. 0.]
 [0. 0. 0. 0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 0. 0. 0. 4.]]
[[9 5 2]
 [5 2 3]
 [1 2 6]]
[[8. 1. 1. 1. 1. 1. 1.]
 [1. 8. 1. 1. 1. 1. 1.]
 [1. 1. 8. 1. 1. 1. 1.]
 [1. 1. 1. 8. 1. 1. 1.]
 [1. 1. 1. 1. 8. 1. 1.]
 [1. 1. 1. 1. 1. 8. 1.]
 [1. 1. 1. 1. 1. 1. 8.]]


In [37]:
# Contoh 2.20.3 Matrix pada Numpy

import numpy as np

# Membuat matriks 3x3 dengan nilai acak
matrix_1_98 = np.random.rand(3, 3)
print('Matriks awal:')
print(matrix_1_98)

# Mengakses elemen matriks
print('Elemen matriks pada baris ke-1, kolom ke-2:', matrix_1_98[0, 1])

# Mengubah elemen matriks
matrix_1_98[0, 1] = 10
print('Matriks setelah mengubah elemen:')
print(matrix_1_98)

# Menjumlahkan dua matriks
matrix_2_98 = np.random.rand(3, 3)
print('Matriks kedua:')
print(matrix_2_98)

hasil_jumlah_98 = matrix_1_98 + matrix_2_98
print('Hasil penjumlahan matriks:')
print(hasil_jumlah_98)

Matriks awal:
[[0.19184301 0.75648534 0.79949805]
 [0.81081252 0.9996676  0.56451595]
 [0.74802446 0.2285325  0.76091319]]
Elemen matriks pada baris ke-1, kolom ke-2: 0.7564853428810172
Matriks setelah mengubah elemen:
[[ 0.19184301 10.          0.79949805]
 [ 0.81081252  0.9996676   0.56451595]
 [ 0.74802446  0.2285325   0.76091319]]
Matriks kedua:
[[0.47217027 0.35908985 0.16486012]
 [0.15331434 0.57535366 0.03242731]
 [0.13320696 0.36550914 0.41917057]]
Hasil penjumlahan matriks:
[[ 0.66401328 10.35908985  0.96435817]
 [ 0.96412686  1.57502126  0.59694326]
 [ 0.88123142  0.59404164  1.18008376]]


In [38]:
# Contoh 2.20.3 Matrix pada Numpy

import numpy as np

kelompok_1_98 = np.full((4,3),2)
print(kelompok_1_98)

kelompok_2_98 = np.ones((5,5))
kelompok_3_98 = np.identity(5)*5
kelompok_4_98 = kelompok_2_98 + kelompok_3_98
print(kelompok_4_98)

[[2 2 2]
 [2 2 2]
 [2 2 2]
 [2 2 2]]
[[6. 1. 1. 1. 1.]
 [1. 6. 1. 1. 1.]
 [1. 1. 6. 1. 1.]
 [1. 1. 1. 6. 1.]
 [1. 1. 1. 1. 6.]]


In [39]:
# Contoh 2.20.4 Copy pada Numpy

import numpy as np

arr_1_98 = np.array([1, 2, 3, 4, 5])
arr_2_98 = arr_1_98.copy()
arr_2_98[0] = 10

print('Array asli:', arr_1_98)
print('Array salinan:', arr_2_98)

Array asli: [1 2 3 4 5]
Array salinan: [10  2  3  4  5]


In [41]:
# Contoh 2.20.4 Copy pada Numpy

import numpy as np

buah_98 = np.array(['apel', 'pisang', 'jeruk', 'anggur', 'mangga'])
sayur_98 = np.array(['wortel', 'kubis', 'bayam', 'terong', 'tomat'])

buah_98_dan_sayur_98 = np.array([buah_98, sayur_98])
salinan_buah_98_dan_sayur_98 = np.copy(buah_98_dan_sayur_98)

print('Array Asli:')
print(buah_98_dan_sayur_98)

print('Array Salinan:')
print(salinan_buah_98_dan_sayur_98)

Array Asli:
[['apel' 'pisang' 'jeruk' 'anggur' 'mangga']
 ['wortel' 'kubis' 'bayam' 'terong' 'tomat']]
Array Salinan:
[['apel' 'pisang' 'jeruk' 'anggur' 'mangga']
 ['wortel' 'kubis' 'bayam' 'terong' 'tomat']]


In [42]:
# Contoh 2.20.4 Copy pada Numpy

import numpy as np

bilangan_one_98 = np.array([1, 2, 3, 8, 10])
bilangan_two_98 = np.array([4, 5, 6, 7, 12])

bilangan_two_98 = np.copy(bilangan_one_98)

print("Bilangan pertama:", bilangan_one_98)
print("Bilangan kedua setelah disalin:", bilangan_two_98)

Bilangan pertama: [ 1  2  3  8 10]
Bilangan kedua setelah disalin: [ 1  2  3  8 10]


In [43]:
# Contoh 2.20.5 Operasi Matematika pada Numpy

import numpy as np

a_98 = np.array([4,2,8,3])
b_98 = np.array([2,5,3,4])

hasil_pertama_98 = a_98 + 5
print('Hasil Pertama:', hasil_pertama_98)

hasil_kedua_98 = a_98 + b_98
print('Hasil Kedua:', hasil_kedua_98)

hasil_ketiga_98 = a_98/2 + b_98
print('Hasil Ketiga:', hasil_ketiga_98)

hasil_keempat_98 = a_98 ** 3/b_98 * 2
print('Hasil Keempat:', hasil_keempat_98)

hasil_kelima_98 = a_98 * b_98
print('Hasil Kelima:', hasil_kelima_98)

hasil_keenam_98 = a_98 - b_98 / a_98
print('Hasil Keenam:', hasil_keenam_98)

Hasil Pertama: [ 9  7 13  8]
Hasil Kedua: [ 6  7 11  7]
Hasil Ketiga: [4.  6.  7.  5.5]
Hasil Keempat: [ 64.           3.2        341.33333333  13.5       ]
Hasil Kelima: [ 8 10 24 12]
Hasil Keenam: [ 3.5        -0.5         7.625       1.66666667]


In [44]:
# Contoh 2.20.5 Operasi Matematika pada Numpy

nilai_satu_98 = np.array([0, np.pi/2, np.pi])

nilai_sin_98 = np.sin(nilai_satu_98)
nilai_cos_98 = np.cos(nilai_satu_98)
nilai_tan_98 = np.tan(nilai_satu_98)

print('Hasil Sin:', nilai_sin_98)
print('Hasil Cos:', nilai_sin_98)
print('Hasil Tan:', nilai_sin_98)

Hasil Sin: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Hasil Cos: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Hasil Tan: [0.0000000e+00 1.0000000e+00 1.2246468e-16]


In [45]:
# Contoh 2.20.5 Operasi Matematika pada Numpy

import numpy as np

a_1_98 = 8
b_2_98 = 5

# Mencari sinus dari dua bilangan
sin_a_1_98 = np.sin(a_1_98)
sin_b_2_98 = np.sin(b_2_98)

# Mencari tangen dari dua bilangan
tan_a_1_98 = np.tan(a_1_98)
tan_b_2_98 = np.tan(b_2_98)

# Mencari kosinus dari dua bilangan
cos_a_1_98 = np.cos(a_1_98)
cos_b_2_98 = np.cos(b_2_98)

# Mencari akar kuadrat dari dua bilangan
sqrt_a_1_98 = np.sqrt(a_1_98)
sqrt_b_2_98 = np.sqrt(b_2_98)

print('Nilai sin dari a:', sin_a_1_98)
print('Nilai sin dari b:', sin_b_2_98)
print('Nilai tan dari a:', tan_a_1_98)
print('Nilai tan dari b:', tan_b_2_98)
print('Nilai cos dari a:', cos_a_1_98)
print('Nilai cos dari b:', cos_b_2_98)
print('Akar kuadrat dari a:', sqrt_a_1_98)
print('Akar kuadrat dari b:', sqrt_b_2_98)

Nilai sin dari a: 0.9893582466233818
Nilai sin dari b: -0.9589242746631385
Nilai tan dari a: -6.799711455220379
Nilai tan dari b: -3.380515006246586
Nilai cos dari a: -0.14550003380861354
Nilai cos dari b: 0.28366218546322625
Akar kuadrat dari a: 2.8284271247461903
Akar kuadrat dari b: 2.23606797749979


In [47]:
# Contoh 2.20.6 Perkalian Matrik pada Numpy

import numpy as np

# Matriks pertama: 2x3
A_1_98 = np.array([[1, 2, 3],
              [4, 5, 6]])

# Matriks kedua: 3x2
B_2_98 = np.array([[7, 8],
              [9, 10],
              [11, 12]])

# Perkalian matriks A dan B
C_3_98 = np.matmul(A_1_98, B_2_98)

print('Hasil perkalian matriks A dan B:')
print(C_3_98)

Hasil perkalian matriks A dan B:
[[ 58  64]
 [139 154]]


In [48]:
# Contoh 2.20.6 Perkalian Matrik pada Numpy

import numpy as np

# Matriks pertama: 3x2
A_1_98 = np.array([[7, 8],
                    [9, 10],
                    [11, 12]])

# Matriks kedua: 2x3
B_2_98 = np.array([[1, 2, 3],
                     [4, 5, 6]])

# Perkalian matriks A dan B
C_3_98 = np.matmul(A_1_98, B_2_98)

print('Hasil perkalian matriks:')
print(C_3_98)

Hasil perkalian matriks:
[[ 39  54  69]
 [ 49  68  87]
 [ 59  82 105]]


In [49]:
# Contoh 2.20.6 Perkalian Matrik pada Numpy

import numpy as np

# Matriks pertama: 2x3
number_1_98 = np.array([[1, 2, 3],
                        [4, 5, 6]])

# Matriks kedua: 3x3
number_2_98 = np.array([[7, 8, 9],
                        [10, 11, 12],
                        [13, 14, 15]])

# Perkalian matriks A dan B
number_3_98 = np.matmul(number_1_98, number_2_98)

print('Hasil perkalian matriks 1 dan 2:')
print(number_3_98)

Hasil perkalian matriks 1 dan 2:
[[ 66  72  78]
 [156 171 186]]


In [50]:
# Contoh 2.20.6 Perkalian Matrik pada Numpy

import numpy as np

# Matriks pertama
nomor_1_98 = np.array([[1, 2],
              [3, 4]])

# Matriks kedua
nomor_2_98 = np.array([[5, 6],
              [7, 8]])

# Melakukan perkalian matriks
nomor_3_98 = np.matmul(nomor_1_98, nomor_2_98)

print('Hasil perkalian matriks:')
print(nomor_3_98)

Hasil perkalian matriks:
[[19 22]
 [43 50]]


In [51]:
# Contoh 2.20.6 Perkalian Matrik pada Numpy

import numpy as np

# Matriks pertama
satu_98 = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Matriks kedua
dua_98 = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

# Melakukan perkalian matriks
tiga_98 = np.matmul(satu_98, dua_98)

print('Hasil perkalian matriks:')
print(tiga_98)

Hasil perkalian matriks:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [52]:
# Contoh 2.20.6 Perkalian Matrik pada Numpy

import numpy as np

# Definisi matriks pertama (3x2)
matrix1_98 = np.array([[1, 2],
                    [3, 4],
                    [5, 6]])

# Definisi matriks kedua (2x2)
matrix2_98 = np.array([[7, 8],
                    [9, 10]])

# Perkalian matriks 
result_matrix_98 = np.matmul(matrix1_98, matrix2_98)

# Tampilkan hasil
print("Hasil perkalian matriks:")
print(result_matrix_98)

Hasil perkalian matriks:
[[ 25  28]
 [ 57  64]
 [ 89 100]]


In [53]:
# Contoh 2.20.6 Perkalian Matrik pada Numpy

import numpy as np

# Matriks jumlah buah (3x2)
jumlah_buah_98 = np.array([[10, 20],
                        [30, 40],
                        [50, 60]])

# Matriks harga per buah (2x1)
harga_per_buah_98 = np.array([[5],
                           [10]])

# Perkalian matriks jumlah buah dengan harga per buah
total_harga_98 = np.matmul(jumlah_buah_98, harga_per_buah_98)

# Tampilkan hasil
print('Total harga buah:')
print(total_harga_98)

Total harga buah:
[[250]
 [550]
 [850]]


In [54]:
# Contoh 2.20.6 Perkalian Matrik pada Numpy

import numpy as np

# Membuat matriks pertama (2x1)
perhitungan_1_98 = np.array([[1, 2]])  

# Membuat matriks kedua (1x2)
perhitungan_2_98 = np.array([[3],
                             [4]])

# Melakukan perkalian matriks
hasil_perkalian_98 = np.matmul(perhitungan_1_98, perhitungan_2_98)

print('Hasil perkalian matriks:')
print(hasil_perkalian_98)

Hasil perkalian matriks:
[[11]]


In [55]:
# Contoh 2.20.6 Perkalian Matrik pada Numpy

import numpy as np

# Membuat matriks kedua (1x2)
perhitungan_1_98 = np.array([[3],
                             [4]])

# Membuat matriks pertama (2x1)
perhitungan_2_98 = np.array([[1, 2]])  

# Melakukan perkalian matriks
hasil_perkalian_98 = np.matmul(perhitungan_1_98, perhitungan_2_98)

print('Hasil perkalian matriks:')
print(hasil_perkalian_98)

Hasil perkalian matriks:
[[3 6]
 [4 8]]


In [56]:
# Contoh 2.20.7 min, max dan sum pada Numpy

import numpy as np

arr_1_98 = np.array([1, 2, 3, 4, 5])

# Minimum dari array
nilai_kecil_98 = np.min(arr_1_98)
print('Nilai minimum:', nilai_kecil_98)

# Maksimum dari array
nilai_besar_98 = np.max(arr_1_98)
print('Nilai maksimum:', nilai_besar_98)

# Jumlah elemen dalam array
jumlah_nilai_98 = np.sum(arr_1_98)
print('Jumlah elemen:', jumlah_nilai_98)

Nilai minimum: 1
Nilai maksimum: 5
Jumlah elemen: 15


In [57]:
# Contoh 2.20.7 min, max dan sum pada Numpy

import numpy as np

bilangan_1_98 = np.array([[2,3,2,7],[1,5,7,3],[2,8,5,3]])
print(bilangan_1_98)

hasil_1_98 = np.min(bilangan_1_98)
print(hasil_1_98)

hasil_2_98 = np.min(bilangan_1_98,axis=0)
print(hasil_2_98)

hasil_3_98 = np.min(bilangan_1_98,axis=1)
print(hasil_3_98)

hasil_4_98 = np.max(bilangan_1_98)
print(hasil_4_98)

hasil_5_98 = np.max(bilangan_1_98,axis=0)
print(hasil_5_98)

hasil_6_98 = np.max(bilangan_1_98,axis=1)
print(hasil_6_98)

hasil_7_98 = np.sum(bilangan_1_98)
print(hasil_7_98)

hasil_8_98 = np.sum(bilangan_1_98,axis=0)
print(hasil_8_98)

hasil_9_98 = np.sum(bilangan_1_98,axis=1)
print(hasil_9_98)

[[2 3 2 7]
 [1 5 7 3]
 [2 8 5 3]]
1
[1 3 2 3]
[2 1 2]
8
[2 8 7 7]
[7 7 8]
48
[ 5 16 14 13]
[14 16 18]


In [58]:
# Contoh 2.20.7 min, max dan sum pada Numpy

import numpy as np

arr_98 = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Mencari nilai minimum dari array
min_value_98 = np.min(arr_98)
print('Nilai minimum:', min_value_98)

# Mencari nilai maksimum dari array
max_value_98 = np.max(arr_98)
print('Nilai maksimum:', max_value_98)

# Menghitung jumlah semua elemen dalam array
sum_value_98 = np.sum(arr_98)
print('Jumlah semua elemen:', sum_value_98)

Nilai minimum: 1
Nilai maksimum: 9
Jumlah semua elemen: 45


In [59]:
# Contoh Numpy

import numpy as np

hitungan_1_98 = np.array([[2, 4, 8, 3], [4, 2, 6, 7]])
print('hitungan_1_98:')
print(hitungan_1_98)

b_98 = np.min(hitungan_1_98)
print('Nilai minimum dari hitungan_1_98:', b_98)

c_98 = hitungan_1_98.copy()
print('Copy dari hitungan_1_98:', c_98)
print(c_98)

c_98[0] = 5
print('c setelah diubah:')
print(c_98)

hitungan_2_98 = np.array([[3, 4, 2, 7], [8, 2, 4, 3]])
print('hitungan_2_98:')
print(hitungan_2_98)

perkalian_nilai_98 = hitungan_1_98 * hitungan_2_98
print('Perkalian elemen matriks hitungan_1_98 dan hitungan_2_98:')
print(perkalian_nilai_98)

hitungan_1_98:
[[2 4 8 3]
 [4 2 6 7]]
Nilai minimum dari hitungan_1_98: 2
Copy dari hitungan_1_98: [[2 4 8 3]
 [4 2 6 7]]
[[2 4 8 3]
 [4 2 6 7]]
c setelah diubah:
[[5 5 5 5]
 [4 2 6 7]]
hitungan_2_98:
[[3 4 2 7]
 [8 2 4 3]]
Perkalian elemen matriks hitungan_1_98 dan hitungan_2_98:
[[ 6 16 16 21]
 [32  4 24 21]]
